name: CI/CD deploy-release

on:
  push:
    branches: [ "deploy-release" ]

jobs:
  ci_cd_deploy_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production --base-href "/RAFAELMH809.github.io/"

      - name: List directory before build
        run: ls -la

      - name: List directory after build
        run: ls -la dist

      - name: List browser directory
        run: ls -la dist/mycv/browser

      - name: Copy new build to docs (without deleting existing files)
        run: |
          rsync -av --ignore-existing dist/mycv/browser/ docs/
      


      - name: Commit and push updated docs
        env:
          CI_COMMIT_MESSAGE: "Deploy actualizado desde deploy-release"
          CI_COMMIT_AUTHOR: "RAFAELMH809"
        run: |
          git config --global user.name "${CI_COMMIT_AUTHOR}"
          git config --global user.email "zS23004693@estudiantes.uv.mx"
          git add .
          git commit -m "${CI_COMMIT_MESSAGE}"
          git push origin deploy-release

