name: CI/CD deploy release
on:
  push:
    branches: [ "deploy-release" ]

jobs:
  ci_cd_deploy_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app for GitHub Pages
        run: npm run build -- --configuration production --base-href "/RAFAELMH809.github.io/"

      - name: Clean old JS/CSS files (no borrar docs enteros)
        run: rm -f docs/*.js docs/*.css docs/*.txt

      - name: Copy build to docs/
        run: cp -ru dist/mycv/browser/* docs/

      - name: Git commit and push docs/
        env:
          CI_COMMIT_MESSAGE: "deploy release to docs/"
          CI_COMMIT_AUTHOR: RAFAELMH809
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "zS23004693@estudiantes.uv.mx"
          git add docs/
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}" || echo "No changes to commit"
          git push origin deploy-release


