name: CI/CD release to Docker

on:
  push:
    branches: [ "release" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app for production
        run: npm run build -- --configuration production --base-href "/"

      - name: Start Apache container
        run: docker run -d --name mycv_container httpd

      - name: Copy build to container
        run: docker cp dist/mycv/browser/. mycv_container:/usr/local/apache2/htdocs/

      - name: Commit Docker image
        run: |
          docker commit --change "ENV MODEL_NAME ${{ secrets.MODEL_NAME }}" \
            mycv_container ${{ secrets.DOCKER_USER }}/${{ secrets.MODEL_NAME }}:${{ github.sha }}

      - name: Login to DockerHub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.MODEL_NAME }}:${{ github.sha }}
